config/routes.rb
Rails.application.routes.draw do
  # namespaceにすることでURLにadminを含む
  namespace :admin do
    root to: 'homes#top'
    resources :members, only: [:index, :show, :edit, :update]
    resources :posts,   only: [:index, :show, :edit, :update]
  end
  # scopeにすることでURLにpublicを含まない
  scope module: :public do
    root to: 'homes#top'
    resources :posts,   except: [:new]
    resources :chats,   only: [:create, :show]
    get 'homes/about'
    get 'relationships/followings'
    get 'relationships/followers'
  end
  
  # 顧客用
  # URL /members/sign_in ...
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :userrooms
  belongs_to :rooms
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :members
    belongs_to :posts
end

app/models/ctiy.rb
class Ctiy < ApplicationRecord
    belongs_to :prefectures
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :members
    belongs_to :posts
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  # has_manyで仮の名前,class_nameで本来のモデル,foreign_keyで参照するカラムを指定
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # viewで使用  上記の仮テーブルを通ってsourceで本来のカラムを参照する
  has_many :followings, through: :followers, source: :followed
  has_many :followers,  through: :followeds, source: :follower
  # DMで使用
  has_many :userrooms
  has_many :chats
  has_many :rooms, through: :userroom

  has_one_attached :image

  # メンバーのプロフィール画像がなければno_imageを適応する
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  # フォローしたときの処理
  def follow(member_id)
    followers.create(followed_id: member_id)
  end
  # フォローを外すときの処理
  def unfollow(member_id)
    followers.find_by(followed_id: member_id).destroy
  end
  # フォローしていればtrueを返す
  def following?(member)
    followings.include?(member)
  end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :member
    has_many   :comments,   dependent: :destroy
    has_many   :favorites,  dependent: :destroy
    has_many   :prefectures,dependent: :destroy
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
    belongs_to :post
    has_many   :cities
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # memberの区別がつかなくなるため,belongs_toで仮の名前,class_nameで本来のモデルを指定
  belongs_to :follower, class_name: "Member"
  belongs_to :followed, class_name: "Member"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :userrooms
  has_many :chats
end

app/models/userroom.rb
class Userroom < ApplicationRecord
  belongs_to :chats
  belongs_to :rooms
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex flex-column">
      <div class="container">
        <div class="navbar">
          <%= link_to "ロゴ", root_path %>
          <ul>
            <li><%= link_to "メンバー", admin_members_path %></li>
            <li><%= link_to "投稿", posts_path %></li>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>